name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: rubycpp1225/ttj
          stage: main
          yaml: >
            name: junback

            app: java@17

            options:
              ports: "9020"
              jarfile: jun_ver2.jar
              env:
                - name: ACCESS_SECRET
                  value: ${{ secrets.ACCESS_SECRET}}
                - name: DB_CLASS
                  value: ${{ secrets.DB_CLASS}}
                - name: DB_PASSWORD
                  value: ${{ secrets.DB_PASSWORD}}
                - name: DB_USER
                  value: ${{ secrets.DB_USER}}
                - name: R_HOST
                  value: ${{ secrets.R_HOST}}
                - name: R_PORT
                  value: ${{ secrets.R_PORT}}
                - name: REFRESH_SECRET
                  value: ${{ secrets.REFRESH_SECRET}}
                - name: DB_URL
                  value: ${{ secrets.DB_URL}}
                - name: AWS_REGION
                  value: ${{ secrets.AWS_REGION}}
                - name: AWS_ACCESS
                  value: ${{ secrets.AWS_ACCESS}}
                - name: AWS_SECRET
                  value: ${{ secrets.AWS_SECRET}}
                - name: AWS_BUCKET_NAME
                  value: ${{ secrets.AWS_BUCKET_NAME}}
                - name: AWS_URL
                  value: ${{ secrets.AWS_URL}}
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
